ame: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Print GITHUB_WORKSPACE
      run: echo "Workspace: $GITHUB_WORKSPACE"
